export const resourcesTopic = {
  id: 'resources',
  displayOrder: 8,
  navLabel: '影音資源',
  title: '韓語自學影音',
  accentColor: 'teal',
  type: 'resources',
  resources: [
    ['韓文40音｜發音技巧大公開（上）', 'YAS3k8FYOsA'],
    ['韓文40音（下）｜分不清的那些子音母音們！', 'OgP8QVhC028'],
    ['韓文40音總整理｜一起唸完子母音399字', '7xALdUCRSX0'],
    ['韓文發音訣竅！掌握2原則', 'FbzpzcOiqcE'],
    ['麵滴Mindy｜韓文四十音，我是這樣學母音', 'UX58vbv3Z1w'],
    ['麵滴Mindy｜韓文四十音，我是這樣學子音', 'i9VYBLDWmQQ'],
    ['麵滴Mindy｜韓文的받침終聲＝收音＝尾音', 'BFMUcb62zuo'],
    ['麵滴Mindy｜發音規則這樣學', 'mZx-u3S6lD8'],
    ['麵滴Mindy｜韓文數字系統—漢式數字', '_coqWSRZR6w'],
    ['麵滴Mindy｜韓文數字系統—韓式固有數字', '-pqV8Hvt2Ys'],
    ['如何用韓文介紹自己與他人', 'pXmQwwVakKY'],
    ['一口氣學會韓劇常用 60 短句', '_ANlTG_XR8k'],
    ['萬用旅行韓語聽力練習', 'UWg7VH38_Us'],
  ].map(([title, videoId], index) => ({
    id: `resource-${String(index + 1).padStart(2, '0')}`,
    title,
    videoId,
    href: `https://www.youtube.com/watch?v=${videoId}`,
    thumbnail: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
  })),
}
